spring.security.user.name=admin
spring.security.user.password=123456
spring.security.user.roles=ADMIN
jwt.secret=MyVerySecureSecretKeyForJWTTokenSigningThatIsLongEnoughToBeSecureFor256BitHMACSHA256Algorithm
jwt.expiration=86400000
